name: DEV

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/dev.yml'

jobs:
  echo:
    environment: DEV
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello"
